### ISSUE TITLE
USE_PSEUDO_FILES cannot be made false with intuitive 0

### ISSUE THREAD

**Issue by languitar** [projectaur/docker-stats-exporter#6]
```
bool(os.environ.get('USE_PSEUDO_FILES', 1))
```
For any non-empty string `bool` returns `True`. As the environment always contains strings, this can never be made `False` with the intuitive example of using 0 instead of 1. You have to redeclare the variable to an empty string, which is a bit counter-intuitive.

**Comment by projectaur** [comment]
Fixed in version 0.7. See https://github.com/projectaur/docker-stats-exporter/commit/bda5c20c9a996146104d980a3bc327fd9dff66ae
